sudo: false
language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

matrix:
    allow_failures:
        - php: 7.1
    fast_finish: true

before_script:
 - composer self-update
 - composer install --prefer-source

script:
  - mkdir -p build/logs
  - mkdir -p build/coverage
  - vendor/bin/phpunit -c tests/phpunit.xml
  - cd ../

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi
